## 单点登录配置START
cas:
  #认证中心地址
  server-url-prefix: sso.op-platform.cn
  #认证中心登录地址
  server-login-url:  sso.op-platform.cn/login
  #后端服务地址
  client-host-url: localhost:9600/spring-cas-client　　　　　
  validation-type: cas









