## 单点登录配置START
cas:
  ##认证中心地址
  server-url-prefix: http://sso.op-platform.cn
  ##认证中心登录地址
  server-login-url:  http://sso.op-platform.cn/login
  ##后端服务地址
  client-host-url: http://localhost:9600
  validation-type: cas3
  ##放开权限









