## 单点登录配置START
cas:
  ##认证中心地址
  server-url-prefix: http://sso.op-platform.cn
  ##认证中心登录地址
  server-login-url:  http://sso.op-platform.cn/login
  ##后端服务地址
  client-host-url: http://localhost:9600
  validation-type: cas3
  ##放开权限
  authentication-url-patterns: /open/*

#自定义的退出url，退出成功后跳转到 http://cas.client1.com:9002/logout/success
casClientLogoutUrl:   http://cas.server.com:8443/cas/logout?service=http://cas.client1.com:9002/logout/success







